sudo: required
dist: trusty
addons:
  apt:
    packages:
      - docker-ce

  sonarcloud:
    organization: "probakilla-github"

notifications:
  email: false

services:
 - docker

language:
  - python

jdk:
  - oraclejdk8

python:
  - "3.5"

before_script:
  - pwd
  - docker-compose up --build -d
  - docker ps -a
  - pip install -r requirements.txt

script:
  - sonar-scanner
  - echo "Pinging containers..."
  - curl localhost:4444
  - curl localhost:8080
  - echo "Stating tests..."
  - python -m pytest test/*.py

after_script:
  - docker-compose down
