sudo: required
dist: trusty
addons:
  apt:
    packages:
      - docker-ce

env:
  DOCKER_COMPOSE_VERSION: 1.23.0

services:
 - docker

language: python
python:
  - "3.3"

install:
  - >
    curl -sSL "https://get.docker.com/gpg" |
    sudo -E apt-key add -
  - >
    echo "deb https://apt.dockerproject.org/repo ubuntu-trusty main" |
     sudo tee -a /etc/apt/sources.list
  - sudo apt-get update
  - >
    sudo apt-get -o Dpkg::Options::="--force-confdef" \
     -o Dpkg::Options::="--force-confold" --assume-yes install docker-engine
  - docker version
  - sudo pip install docker-compose
  - docker-compose version

before_script:
  - sudo docker-compose up -d
  - docker --version
  - pip install -r requirements.txt

script:
  - echo "Init containers..."
  - sleep 15
  - curl localhost:4444
  - curl localhost:8080
  - echo "Stating tests..."
  - python -m pytest test/*.py

after_script:
  - docker-compose down
