sudo: required
dist: trusty
addons:
  apt:
    packages:
      - docker-ce

  sonarcloud:
    organization: "probakilla-github"

notifications:
  email: false

services:
 - docker

language:
  - python

jdk:
  - oraclejdk8

python:
  - "3.5"

before_script:
  - docker-compose up --build -d
  - pip install -r requirements.txt
  - composer update

script:
  - sonar-scanner
  - vendor/bin/phpcbf src/php/**
  - vendor/bin/phpcs src/php/models/*
  - echo "Stating tests..."
  - python -m pytest test/*.py

after_script:
  - docker-compose down
