sudo: required
addons:
  apt:
    packages:
      - docker-ce

services:
  docker

language: php
php:
  - '7.0'
  - nightly

before-install:
  - pwd
  - ls -la
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar require squizlabs/php_codesniffer
  - docker-compose up -d

script:
  - echo "Linting project ..."
  - vendor/bin/phpcs src/php/*