sudo: required
addons:
  apt:
    packages:
      - docker-ce

services:
 - docker

language: python
python:
  - "3.5"

before-install:
  - pwd
  - ls -la
  - docker-compose up -d
  - pip install selenium

script:
  - echo "Stating tests ..."
  - echo "NO TESTS YET"
