sudo: required
addons:
  apt:
    packages:
      - docker-ce

services:
 - docker

language: python
python:
  - "3.3"

before-install:
  - pwd
  - ls -la
  - sudo docker-compose up -d
  - docker --version
  - pip install -r requirements.txt

script:
  - echo "Init containers..."
  - sleep 15
  - curl localhost:4444
  - curl localhost:8080
  - echo "Stating tests..."
  - python -m pytest test/*.py
