sudo: required
dist: trusty
addons:
  apt:
    packages:
      - docker-ce

services:
 - docker

language: python
python:
  - "3.5"

before_script:
  - pwd
  - docker-compose up --build -d
  - docker ps -a
  - sleep 30
  - pip install -r requirements.txt

script:
  - echo "Pinging containers..."
  - curl localhost:4444
  - curl localhost:8080
  - echo "Stating tests..."
  - python -m pytest test/*.py

after_script:
  - docker-compose down
