version: "3"
services:
  mariadb:
    image: mariadb:10.1
    container_name: mariadb
    environment:
      MYSQL_DATABASE: CdP
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - mariadb:/var/lib/mysql
      - ./src/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always

  php-apache:
    build:
      context: "docker/php-apache"
    container_name: php
    ports:
      - 8080:80
    volumes:
      - ./src:/var/www/html
    links:
      - mariadb

  chrome:
    image: selenium/node-chrome:3.14.0-gallium
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - hub
    links:
      - php-apache
    environment:
      HUB_HOST: hub

  hub:
    image: selenium/hub:3.14.0-gallium
    ports:
      - "4444:4444"
    links:
      - php-apache

volumes:
  mariadb:
